
const DB_KEY="addrway_demo_db",SESSION_KEY="addrway_session";
function seedDB(){const e=localStorage.getItem(DB_KEY);if(e)return JSON.parse(e);const db={users:[{id:"admin-1",name:"Luis",email:"admin@addrway.com",password:"admin123",role:"admin",plan:"Business",status:"Active",lookupsUsed:18942,createdAt:"2026-04-01T10:00:00Z"},{id:"u-101",name:"Sarah Johnson",email:"sarah@northship.com",password:"demo123",role:"customer",plan:"Pro",status:"Active",lookupsUsed:5122,createdAt:"2026-04-06T11:00:00Z"},{id:"u-102",name:"Marcus Lee",email:"marcus@atlasops.io",password:"demo123",role:"customer",plan:"Free",status:"Near Limit",lookupsUsed:824,createdAt:"2026-04-08T14:20:00Z"},{id:"u-103",name:"Nina Patel",email:"nina@parcelpath.com",password:"demo123",role:"customer",plan:"Business",status:"Active",lookupsUsed:12947,createdAt:"2026-04-09T08:10:00Z"},{id:"u-104",name:"David Morris",email:"david@sunroute.com",password:"demo123",role:"customer",plan:"Free",status:"Idle",lookupsUsed:106,createdAt:"2026-04-10T18:00:00Z"}],lookups:[{id:"l-1",userId:"u-101",address:"1258 Maple Ave, Tampa, FL 33602",result:"Valid",cached:false,createdAt:"2026-04-19T19:02:00Z"},{id:"l-2",userId:"u-102",address:"890 Harbor Dr, Miami, FL 33101",result:"Review",cached:false,createdAt:"2026-04-19T19:10:00Z"},{id:"l-3",userId:"u-103",address:"4410 Cypress Rd, Austin, TX 78701",result:"Valid",cached:true,createdAt:"2026-04-19T19:18:00Z"},{id:"l-4",userId:"u-104",address:"17 Ocean Blvd, Newark, NJ 07102",result:"Invalid",cached:false,createdAt:"2026-04-19T19:31:00Z"},{id:"l-5",userId:"admin-1",address:"700 Water St, Tampa, FL 33602",result:"Valid",cached:true,createdAt:"2026-04-19T19:36:00Z"}]};localStorage.setItem(DB_KEY,JSON.stringify(db));return db}
function getDB(){return JSON.parse(localStorage.getItem(DB_KEY)||JSON.stringify(seedDB()))}function saveDB(db){localStorage.setItem(DB_KEY,JSON.stringify(db))}
function setSession(u){localStorage.setItem(SESSION_KEY,JSON.stringify({id:u.id,role:u.role}))}function getSession(){return JSON.parse(localStorage.getItem(SESSION_KEY)||"null")}
function logout(){localStorage.removeItem(SESSION_KEY);window.location.href="login.html"}function currentUser(){const s=getSession();if(!s)return null;return getDB().users.find(u=>u.id===s.id)||null}
function requireAuth(role){const u=currentUser();if(!u){window.location.href="login.html";return null}if(role&&u.role!==role){window.location.href=u.role==="admin"?"admin.html":"customer-dashboard.html";return null}return u}
function formatTime(i){return new Date(i).toLocaleString([],{month:"short",day:"numeric",hour:"numeric",minute:"2-digit"})}
function badgeClass(s){const v=String(s).toLowerCase();if(["active","valid","business","pro","successful"].includes(v))return"badge-good";if(["near limit","review","free","warning"].includes(v))return"badge-warn";if(["invalid","failed","suspended"].includes(v))return"badge-bad";return"badge-neutral"}
function userNameById(id){const u=getDB().users.find(u=>u.id===id);return u?u.name:"Unknown"}
function createLookup(address,userId){const db=getDB();const cached=db.lookups.some(l=>l.address.toLowerCase()===address.toLowerCase());let result="Valid";if(address.length<10)result="Review";if(address.toLowerCase().includes("invalid"))result="Invalid";const lookup={id:"l-"+Date.now(),userId,address,result,cached,createdAt:new Date().toISOString()};db.lookups.unshift(lookup);const u=db.users.find(u=>u.id===userId);if(u)u.lookupsUsed+=1;saveDB(db);return lookup}
function navHTML(active){return [["admin.html","Dashboard"],["admin-users.html","Users"],["admin-lookups.html","Lookups"],["analytics.html","Analytics"],["billing.html","Billing"],["system.html","System Health"],["settings.html","Settings"]].map(([h,l])=>`<a href="${h}" class="${active===l?'active':''}">${l}</a>`).join("")}
function customerNavHTML(active){return [["customer-dashboard.html","Dashboard"],["lookup.html","Lookup"],["history.html","History"],["settings.html","Settings"]].map(([h,l])=>`<a href="${h}" class="${active===l?'active':''}">${l}</a>`).join("")}
